### ISSUE TITLE
Decouple from sklearn, make just a black-box optimizer

### ISSUE THREAD

**Issue by KOLANICH** [jclevesque/bayes_ens_opt#1]

**Comment by jclevesque** [comment]
Hi! Thanks for opening an issue. This package is not a standalone black-box optimizer. It is hyperparameter optimization directly aimed at generating ensembles of classifiers. If you are looking for a black-box optimization toolbox, you should look elsewhere. My code uses an old version of spearmint, you could use their toolbox (https://github.com/HIPS/Spearmint), but there are plenty of other options out there. 

As for Sklearn, it is used for some util functions (metrics etc.). The sklearn classifiers are not required, although I do use them in the examples for convenience.

Note that this code is provided mostly for research purposes, I don't plan on maintaining it.

**Comment by KOLANICH** [comment]
Hi!

>but there are plenty of other options out there

I know. You may find [my framework](https://gitlab.com/KOLANICH/UniOpt.py) unifying their API useful.

>My code uses an old version of spearmint

Thank you for the clarification, I already use it.
